```{r setup, include=FALSE}
if (!require("pacman")) install.packages("pacman")
p_load(data.table, dplyr, tidyr)
p_load(ggplot2)
p_load(CausalImpact, zoo)
`%+%` <- function(x,y){ paste0(x, y)}
```

```{r}
path <- '0-Data/doge-data-1.csv'
d <- fread(path) 
d[,date := as.POSIXct(date, tz = 'UTC')]
```
# Interventions (Events)
```{r}
tweets <- as.POSIXct(
  c(
  '2021-01-28 22:47:00 UTC',
  '2021-02-04 07:29:00 UTC',
  '2021-02-04 08:15:00 UTC',
  '2021-02-04 07:57:00 UTC',
  '2021-02-04 08:27:00 UTC'
  ), tz = 'UTC'
)
```
# Compile Datasets
```{r}
d.doge <- d[crypto %in% 'Dogecoin',]
d.bit <- d[crypto %in% 'Bitcoin',]

d.bit[,price := (price - mean(price))/sd(price)]
d.bit[,price := (low - mean(low))/sd(low)]
d.doge[,price := (price - mean(price))/sd(price)]

d <- data.table(dodge_price = d.doge$price,
                google_interest = d.bit$price,
                google_interest_musk = d.bit$low,
                date = d.bit$date
                )
```

```{r}
ggplot(d) +
  geom_line(aes(x = date, y = dodge_price, col = "Dogecoin")) +
  geom_line(aes(x = date, y = google_interest, col = "Google Trends")) + 
  geom_vline(xintercept = tweets[1])
```

```{r}
times <- d$date
d[,date := NULL]
d <- zoo(d,times)
```

```{r}
tweet_ix <- which(times == tweets[1])

fit <- CausalImpact(
    data = d,
    pre.period = times[c(1, tweet_ix)],
    post.period = times[c(tweet_ix + 1, length(times))]
  )
  
summary(fit)
plot(fit)
# Select subset of data for analysis
start_analysis <- as.POSIXct('2021-01-28 11:00:00 UTC', tz = 'UTC')
end_analysis <- as.POSIXct('2021-01-29 01:00:00 UTC', tz = 'UTC')
datsel <- filter(dat, between(date, start_analysis, end_analysis))
 
fit1 <- fit_model(datsel, tweets[1])
plot(fit1, 'original') +
  xlab('Time') +
  ylab('Price (€)') +
  ggtitle('Tweeting about Dogecoin (28th January)') +
  theme(
    axis.text = element_text(size = 10),
    axis.title = element_text(size = 10),
    plot.title = element_text(size = 10, hjust = 0.50)
  )
plot(fit1)
```

