---
title: "Google Trends: Echo-of-Moscow"
author: "Anton Sobolev"
output:
  html_document: default
  pdf_document: default
---
### Prepare data
### Packages
```{r, include=FALSE}
if (!require("pacman")) install.packages("pacman")
p_load(data.table, dplyr, tidyr, gtrendsR, drat)
drat:::add("ghrr") 
library(gtrendsR)
library(devtools)
install_github('zachokeeffe/gtrendsR',force=T)
```
### Load data

```{r}
location <- hits <- keyword <- geo <- gprop <- NA
d.bin <- cbind(location,hits, keyword,geo,gprop) %>% data.table()
days <- seq(as.Date("2011-12-01"), as.Date("2012-03-30"), by="days")
next.days <- seq(as.Date("2011-12-02"), as.Date("2012-03-31"), by="days")
dates <- paste(days,next.days)
i = 1
for(date in dates){
print(i)
trend <- gtrends(c("эхо москвы") , geo = "RU",
                 time=date,gprop='web',category=0)
d.bin <- rbind(d.bin, trend$interest_by_region) %>% data.table()
i = i + 1
}
d.bin <- d.bin[-1,]
```

```{r}
fwrite(d.bin,"echo-of-moscow-google-trends.csv", row.names = F, quote = F, append = F)
```

